const mongoose = require("mongoose");
mongoose.Promise = global.Promise;
const modelStore = {};
modelStore.mongoose = mongoose;
modelStore.user = require("./user.model");
modelStore.role = require("./role.model");
modelStore.ROLES = ["user"];
modelStore.travelItem = require("./travelItem.model");
module.exports = modelStore;
